### ISSUE TITLE
App immediately crashes on first start after install. [android]

### ISSUE THREAD

**Issue by rahulgi** [rahafoundation/raha-mobile-app#221]
Is anyone else seeing this happen?

On the first startup after installing the app on Android, the app always crashes on my phone. This does not occur again, even after restarting the phone.

Phone logs seem to indicate an issue with initializing Firebase.

I think this might be related to our upgrade to RN 0.56. We did not upgrade React-Native-Firebase alongside it, though RNF states that we need to upgrade to version 5.0.0(rc) if we are using RN 0.56. Currently we are on 4.3. I started working on #220 to do this upgrade, but am having compilation issues. @tinaroh if you have time, would you be down to help me figure those out? I am pretty newb at debugging build issues.

**Comment by rahulgi** [comment]
The logs from logcat look like:

```
08-23 18:24:54.226 26234-26286/? E/cr_VariationsUtils: Failed reading seed file "/data/user/0/app.raha.mobileProd/app_webview/variations_seed_new": /data/user/0/app.raha.mobileProd/app_webview/variations_seed_new (No such file or directory)
    Failed reading seed file "/data/user/0/app.raha.mobileProd/app_webview/variations_seed": /data/user/0/app.raha.mobileProd/app_webview/variations_seed (No such file or directory)
08-23 18:24:54.283 26289-26289/? E//system/bin/webview_zygote32: Failed to make and chown /acct/uid_99039: Permission denied
08-23 18:24:54.284 26289-26289/? E/Zygote: createProcessGroup(99039, 0) failed: Permission denied
08-23 18:24:54.346 26307-26307/? E/asset: setgid: Operation not permitted
08-23 18:24:55.126 26234-26234/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: app.raha.mobileProd, PID: 26234
    java.lang.IllegalStateException: Default FirebaseApp is not initialized in this process app.raha.mobileProd. Make sure to call FirebaseApp.initializeApp(Context) first.
        at com.google.firebase.FirebaseApp.getInstance(SourceFile:218)
        at com.google.firebase.iid.FirebaseInstanceId.getInstance(Unknown Source:0)
        at io.invertase.firebase.messaging.RNFirebaseMessaging$RefreshTokenReceiver.onReceive(RNFirebaseMessaging.java:155)
        at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:308)
        at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:46)
        at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:118)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by tinaroh** [comment]
I don't think this is a build issue -- it's a runtime issue. Where is FirebaseApp.initializeApp(Context) called? We should try to do it as early in the application lifecycle as possible

**Comment by tinaroh** [comment]
Just reproduced this. I'll try to fix the build issues on your branch

**Comment by rahulgi** [comment]
Woah, awesome, thanks @tinaroh!

**Comment by vinamrax** [comment]
Hey,
I'm getting same error can you please help me out?
